import { Router,Response } from "express";
import { getRepositories } from "../repositories";
import { AuthedRequest,authenticate } from "../middleware/auth";
import { generateArchitecture,validateArchitectureContent } from "../services/architectureAgent";
import { generateBusinessAnalysis,validateBusinessAnalysisContent } from "../services/businessAnalysis";
import { validateIdea } from "../services/consultant";
import { generateDataModel,validateDataModeling } from "../services/dataModelingAgent";
import { isValidSvg,renderToSvg } from "../services/diagramRenderer";
import { discoveryAsk } from "../services/discoveryAgent";
import { embed } from "../services/documentParser";
import { generateEstimation,validateEstimationContent } from "../services/estimationAgent";
import { generateRoadmap,validateRoadmapContent } from "../services/plannerAgent";
import { generateProcess,validateBpmnJson } from "../services/processAgent";
import { generateUx,validateUx } from "../services/uxAgent";
const router=Router();
const language=(req:AuthedRequest)=>((req as any).lang||(req.query.lang as string)||req.headers["accept-language"]?.split(",")[0]?.split(";")[0]?.trim()||"en");
async function project(req:AuthedRequest,id?:string){if(!id)return null;return getRepositories().projects.findProjectById(req.user!.orgId,String(id));}
async function context(orgId:string,projectId:string,query?:string){if(!query)return undefined;const hits=await getRepositories().documents.searchSimilarChunks(orgId,projectId,embed(query),5);return hits.map(h=>h.content);}
router.post("/ai/v1/discovery/ask",authenticate,async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,b=req.body||{};let history:( {role:"user"|"ai";content:string})[]=[];let projectId=b.projectId?String(b.projectId):undefined;if(b.conversationId){const c=await getRepositories().conversations.findById(orgId,String(b.conversationId));if(c){projectId=c.projectId;history=(await getRepositories().conversations.listMessages(orgId,c.id)).map(m=>({role:m.role,content:m.content}));}}else if(typeof b.query==="string")history=[{role:"user",content:b.query}];const ragContext=projectId?await context(orgId,projectId,history.at(-1)?.content):undefined;res.json(await discoveryAsk({conversationHistory:history,ragContext,projectId,orgId,lang:language(req)}));});
router.post("/ai/v1/business-analysis/generate",authenticate,async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,userId=req.user!.userId,b=req.body||{},p=await project(req,b.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});let history:any;if(b.conversationId){const c=await getRepositories().conversations.findById(orgId,String(b.conversationId));if(c)history=(await getRepositories().conversations.listMessages(orgId,c.id)).map(m=>({role:m.role,content:m.content}));}const excerpts=typeof b.query==="string"?await context(orgId,p.id,b.query):undefined;const r=await generateBusinessAnalysis({projectId:p.id,orgId,conversationHistory:history,documentExcerpts:excerpts,createdBy:userId});return res.status(201).json({...r,type:"business_analysis",status:"draft",validation:validateBusinessAnalysisContent(r.content),generatedBy:"ai"});});
router.post("/ai/v1/consultant/validate-idea",authenticate,async(req:AuthedRequest,res:Response)=>{if(typeof req.body?.idea!=="string"||!req.body.idea.trim())return res.status(400).json({error:{code:"BAD_REQUEST",message:"idea required"}});return res.json(validateIdea({idea:req.body.idea,context:req.body.context,lang:language(req)}));});
router.post("/ai/v1/architecture/generate",authenticate,async(req:AuthedRequest,res:Response)=>{const p=await project(req,req.body?.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const type=(req.body?.type||"architecture_hld") as "architecture_hld"|"architecture_lld";const r=await generateArchitecture({projectId:p.id,orgId:req.user!.orgId,type,params:req.body?.params,createdBy:req.user!.userId});return res.status(201).json({...r,type,status:"draft",validation:validateArchitectureContent(r.content),generatedBy:"ai"});});
router.post("/ai/v1/process/generate-workflow",authenticate,async(req:AuthedRequest,res:Response)=>{const p=await project(req,req.body?.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const r=await generateProcess({projectId:p.id,orgId:req.user!.orgId,createdBy:req.user!.userId,params:req.body?.params});return res.status(201).json({...r,type:"process_workflow",status:"draft",validation:validateBpmnJson(r.content),generatedBy:"ai"});});
router.post("/ai/v1/data-model/generate",authenticate,async(req:AuthedRequest,res:Response)=>{const p=await project(req,req.body?.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const r=await generateDataModel({projectId:p.id,orgId:req.user!.orgId,createdBy:req.user!.userId,params:req.body?.params});return res.status(201).json({...r,type:"er_diagram",status:"draft",validation:validateDataModeling(r.content),generatedBy:"ai"});});
router.post("/ai/v1/ux/generate-wireframes",authenticate,async(req:AuthedRequest,res:Response)=>{const p=await project(req,req.body?.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const r=await generateUx({projectId:p.id,orgId:req.user!.orgId,createdBy:req.user!.userId,params:req.body?.params});return res.status(201).json({...r,type:"wireframe",status:"draft",validation:validateUx(r.content),generatedBy:"ai"});});
router.post("/ai/v1/diagram/render",authenticate,async(req:AuthedRequest,res:Response)=>{try{if(!req.body?.diagramSpec||!Array.isArray(req.body.diagramSpec.nodes))return res.status(400).json({error:{code:"BAD_REQUEST",message:"diagramSpec required"}});const svg=renderToSvg(req.body.diagramSpec);if(!isValidSvg(svg))throw new Error("Generated SVG invalid");return res.json({svg,valid:true});}catch(e){return res.status(400).json({error:{code:"BAD_REQUEST",message:(e as Error).message}});}});
router.post("/ai/v1/planning/generate-roadmap",authenticate,async(req:AuthedRequest,res:Response)=>{const p=await project(req,req.body?.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const r=await generateRoadmap({projectId:p.id,orgId:req.user!.orgId,createdBy:req.user!.userId,params:req.body?.params});return res.status(201).json({...r,type:"roadmap",status:"draft",validation:validateRoadmapContent(r.content),generatedBy:"ai"});});
router.post("/ai/v1/planning/estimate",authenticate,async(req:AuthedRequest,res:Response)=>{const p=await project(req,req.body?.projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const r=await generateEstimation({projectId:p.id,orgId:req.user!.orgId,createdBy:req.user!.userId,scope:req.body?.scope,artifactId:req.body?.artifactId});return res.status(201).json({...r,type:"effort_estimate",status:"draft",validation:validateEstimationContent(r.content),generatedBy:"ai"});});
export default router;
