import { Router, Response } from "express";
import { getRepositories } from "../repositories";
import { AuthedRequest, authenticate } from "../middleware/auth";
import { authorize } from "../middleware/rbac";
import { discoveryAsk } from "../services/discoveryAgent";
import { embed } from "../services/documentParser";
import { rateLimit } from "../middleware/rateLimit";
const router=Router();
const langOf=(req:AuthedRequest)=>((req as any).lang||(req.query.lang as string)||req.headers["accept-language"]?.split(",")[0]?.split(";")[0]?.trim()||"en");
const access=["org_admin","workspace_admin","contributor","reviewer","viewer"] as const;
async function checkMember(orgId:string,projectId:string,userId:string,role:string){ if(role==="org_admin"||role==="workspace_admin") return true; try{ const ms=await getRepositories().projects.listMembers(orgId,projectId); if(ms.length===0) return true; return ms.some(m=>m.userId===userId);}catch{return true;}}
router.post("/projects/:id/conversations",authenticate,authorize(...access),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,userId=req.user!.userId,projectId=String(req.params.id);const p=await getRepositories().projects.findProjectById(orgId,projectId);if(!p)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});if(!(await checkMember(orgId,projectId,userId,req.user!.role))) return res.status(403).json({error:{code:"FORBIDDEN",message:"Not a project member"}});const c=await getRepositories().conversations.create(orgId,projectId,userId);return res.status(201).json(c);});
router.get("/conversations/:id",authenticate,authorize(...access),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,c=await getRepositories().conversations.findById(orgId,String(req.params.id));if(!c)return res.status(404).json({error:{code:"NOT_FOUND",message:"Conversation not found"}});const messages=await getRepositories().conversations.listMessages(orgId,c.id);return res.json({...c,messages});});
router.get("/conversations/:id/messages",authenticate,authorize(...access),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,c=await getRepositories().conversations.findById(orgId,String(req.params.id));if(!c)return res.status(404).json({error:{code:"NOT_FOUND",message:"Conversation not found"}});return res.json({data:await getRepositories().conversations.listMessages(orgId,c.id)});});
router.post("/conversations/:id/messages",authenticate,rateLimit({limit:30}),authorize(...access),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,c=await getRepositories().conversations.findById(orgId,String(req.params.id));if(!c)return res.status(404).json({error:{code:"NOT_FOUND",message:"Conversation not found"}});const content=typeof req.body?.content==="string"?req.body.content.trim():"";if(!content)return res.status(400).json({error:{code:"BAD_REQUEST",message:"content required"}});const repo=getRepositories().conversations;const userMessage=await repo.addMessage(orgId,c.id,"user",content);const history=(await repo.listMessages(orgId,c.id)).map(m=>({role:m.role as "user"|"ai",content:m.content}));const docs=await getRepositories().documents.listDocumentsByProject(orgId,c.projectId);let ragContext:string[]|undefined;let citations:Array<{documentId:string;chunkId:string;chunkText:string;page?:number;score?:number}>=[];if(docs.length){const hits=await getRepositories().documents.searchSimilarChunks(orgId,c.projectId,embed(content),5);ragContext=hits.map(h=>h.content);citations=hits.map(h=>({documentId:h.documentId,chunkId:h.id,chunkText:h.content,page:(h as any).page_number||(h as any).pageRef||1,score:(h as any).score||0.9}));}const aiResult=await discoveryAsk({conversationHistory:history,ragContext,projectId:c.projectId,orgId,lang:langOf(req)});const aiContent=aiResult.type==="question"?aiResult.question:`Summary: ${aiResult.summary}\nStructured: ${JSON.stringify(aiResult.structured)}`;const aiMessage=await repo.addMessage(orgId,c.id,"ai",aiContent);return res.status(201).json({id:aiMessage.id,role:"ai",content:aiContent,citations,userMessage,aiMessage,aiResult});});
export default router;
