import { Router,Response } from "express";
import multer from "multer";
import { getRepositories } from "../repositories";
import { AuthedRequest,authenticate } from "../middleware/auth";
import { authorize } from "../middleware/rbac";
import { processDocument,embed } from "../services/documentParser";
import { storeFile,getMemoryFile,generateSignedUrl,deleteFile } from "../services/storage";
import { rateLimit } from "../middleware/rateLimit";
const router=Router();const MAX_FILE_SIZE=10*1024*1024;const ALLOWED=new Set(["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.presentationml.presentation","text/plain"]);const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_FILE_SIZE},fileFilter:(_req,file,cb)=>cb(null,ALLOWED.has(file.mimetype))});
const error=(res:Response,status:number,code:string,message:string)=>res.status(status).json({error:{code,message}});const fileType=(f:string)=>{const e=f.toLowerCase().split(".").pop();return e==="pdf"||e==="docx"||e==="pptx"?e:"other";};
async function checkProjectMember(orgId:string,projectId:string,userId:string,role:string){ if(role==="org_admin"||role==="workspace_admin") return true; try{ const ms=await getRepositories().projects.listMembers(orgId,projectId); if(ms.length===0) return true; return ms.some(m=>m.userId===userId);}catch{ return true;}}
router.post("/projects/:id/documents",authenticate,rateLimit({limit:20}),authorize("org_admin","workspace_admin","contributor"),upload.single("file"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,projectId=String(req.params.id);if(!(await getRepositories().projects.findProjectById(orgId,projectId)))return error(res,404,"NOT_FOUND","Project not found");if(!(await checkProjectMember(orgId,projectId,req.user!.userId,req.user!.role))) return error(res,403,"FORBIDDEN","Not a project member");const file=req.file;if(!file)return error(res,400,"BAD_REQUEST","A supported file is required");const filename=file.originalname||"document";const stored=await storeFile(orgId,file.buffer,filename,file.mimetype);const doc=await getRepositories().documents.createDocument(orgId,projectId,{filename,docType:fileType(filename),fileSize:file.size,storageKey:stored.storageUrl,uploadedBy:req.user!.userId});const run=async()=>{try{const cs=await processDocument({documentId:doc.id,orgId,buffer:file.buffer,filename});await getRepositories().documents.addChunks(orgId,doc.id,cs.map((c,i)=>({chunkIndex:i,content:c.chunkText,pageNumber:c.pageRef??undefined,embedding:c.embedding})));await getRepositories().documents.updateParsedStatus(orgId,doc.id,"parsed");}catch(e){console.error(`Document processing failed [${doc.id}]`,e);await getRepositories().documents.updateParsedStatus(orgId,doc.id,"failed").catch(()=>undefined);}};if(req.query.sync==="true"||process.env.NODE_ENV==="test")await run();else void run();return res.status(201).json({...doc,doc_type:doc.type,type:doc.type,storageUrl:stored.storageUrl,signedUrl:await generateSignedUrl(doc.id,orgId,stored.storageUrl)});});
router.get("/projects/:id/documents",authenticate,authorize("org_admin","workspace_admin","contributor","reviewer","viewer"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,projectId=String(req.params.id);if(!(await getRepositories().projects.findProjectById(orgId,projectId)))return error(res,404,"NOT_FOUND","Project not found");if(!(await checkProjectMember(orgId,projectId,req.user!.userId,req.user!.role))) return error(res,403,"FORBIDDEN","Not a project member");const docs=await getRepositories().documents.listDocumentsByProject(orgId,projectId);const page=Math.max(1,Number.parseInt(String(req.query.page||"1"),10)||1),pageSize=Math.max(1,Math.min(100,Number.parseInt(String(req.query.page_size||"20"),10)||20));const data=await Promise.all(docs.slice((page-1)*pageSize,page*pageSize).map(async d=>({...d,doc_type:d.type,type:d.type,signedUrl:await generateSignedUrl(d.id,orgId,d.storage_key||"")})));return res.json({data,page,page_size:pageSize,total:docs.length});});
router.get("/documents/:id",authenticate,authorize("org_admin","workspace_admin","contributor","reviewer","viewer"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,d=await getRepositories().documents.findDocumentById(orgId,String(req.params.id));if(!d)return error(res,404,"NOT_FOUND","Document not found");return res.json({...d,doc_type:d.type,type:d.type,signedUrl:await generateSignedUrl(d.id,orgId,d.storage_key||"")});});
router.delete("/documents/:id",authenticate,authorize("org_admin","workspace_admin","contributor"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,repo=getRepositories().documents,d=await repo.findDocumentById(orgId,String(req.params.id));if(!d)return error(res,404,"NOT_FOUND","Document not found");await deleteFile(orgId,d.storage_key||"");await repo.deleteDocument(orgId,d.id);return res.status(204).send();});
router.get("/documents/:id/status",authenticate,authorize("org_admin","workspace_admin","contributor","reviewer","viewer"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId;const d=await getRepositories().documents.findDocumentById(orgId,String(req.params.id));if(!d)return error(res,404,"NOT_FOUND","Document not found");const chunkCount=await getRepositories().documents.getChunkCount(orgId,d.id);return res.json({id:d.id,parsedStatus:d.parsedStatus,chunkCount});});
router.get("/documents/:id/file",authenticate,authorize("org_admin","workspace_admin","contributor","reviewer","viewer"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,d=await getRepositories().documents.findDocumentById(orgId,String(req.params.id));if(!d)return error(res,404,"NOT_FOUND","Document not found");if(d.storage_key?.startsWith("s3://"))return res.redirect(307,await generateSignedUrl(d.id,orgId,d.storage_key));if(process.env.NODE_ENV==="production")return error(res,503,"STORAGE_UNAVAILABLE","Object storage is unavailable");const m=d.storage_key?.match(/^memory:\/\/documents\/([^/]+)/),f=m?getMemoryFile(m[1]!):undefined;if(!f)return error(res,404,"NOT_FOUND","File not found");res.setHeader("Content-Type",f.mimetype);res.setHeader("Content-Disposition",`attachment; filename="${f.filename.replace(/"/g,"")}"`);return res.send(f.buffer);});
router.post("/projects/:id/rag/search",authenticate,authorize("org_admin","workspace_admin","contributor","reviewer","viewer"),async(req:AuthedRequest,res:Response)=>{const orgId=req.user!.orgId,projectId=String(req.params.id);if(!(await getRepositories().projects.findProjectById(orgId,projectId)))return error(res,404,"NOT_FOUND","Project not found");const query=typeof req.body?.query==="string"?req.body.query.trim():"",k=Math.max(1,Math.min(20,Number(req.body?.k)||5));if(!query)return error(res,400,"BAD_REQUEST","query required");const results=await getRepositories().documents.searchSimilarChunks(orgId,projectId,embed(query),k);return res.json({query,k,results:results.map(r=>({id:r.id,documentId:r.documentId,orgId:r.orgId,chunkText:r.content,pageRef:r.page_number,score:r.score})),total:results.length});});
router.post("/projects/:id/rag/evaluate",authenticate,authorize("org_admin","workspace_admin","contributor","reviewer","viewer"),async(req:AuthedRequest,res:Response)=>{
  const orgId=req.user!.orgId,projectId=String(req.params.id);
  if(!(await getRepositories().projects.findProjectById(orgId,projectId)))return error(res,404,"NOT_FOUND","Project not found");
  const claims = Array.isArray((req.body as {claims?:string[]})?.claims) ? (req.body as {claims:string[]}).claims : [];
  const query = typeof (req.body as {query?:string})?.query === "string" ? String((req.body as {query:string}).query).trim() : (claims.join(" ") || "evaluation");
  const k = Math.max(1, Math.min(20, Number((req.body as {k?:number})?.k) || 5));
  const hits = await getRepositories().documents.searchSimilarChunks(orgId,projectId,embed(query),k);
  const sources = hits.map(h=>({id:h.id,documentId:h.documentId,orgId:h.orgId,chunkText:h.content,pageRef:(h as unknown as {page_number?:number}).page_number ?? 1,score:(h as unknown as {score?:number}).score ?? 0.9}));
  // Use rag verifyClaimGrounding for citation correctness
  const { verifyClaimGrounding, detectUnsupportedClaims } = await import("../services/rag");
  const verified = claims.length ? verifyClaimGrounding(claims, sources as unknown as Parameters<typeof verifyClaimGrounding>[1]) : [];
  const unsupported = claims.length ? detectUnsupportedClaims(claims, sources as unknown as Parameters<typeof detectUnsupportedClaims>[1]) : [];
  const grounded = verified.filter(v=>v.isSupported).length;
  const recall = verified.length ? grounded/verified.length : 0;
  const precision = sources.length ? grounded / Math.max(1, sources.length) : 0;
  return res.json({ query, k, sources: sources.length, verified, unsupported, metrics:{ recall, precision, grounded, totalClaims: verified.length, unsupportedClaims: unsupported.length, citationCorrectness: recall } });
});
export default router;
