import { API_BASE } from "@bta/shared";
export const API_BASE_URL = API_BASE;
export interface FetchOptions extends RequestInit { token?: string; }
export async function apiFetch(path: string, opts: FetchOptions = {}): Promise<Response> { const headers: Record<string, string> = { ...(opts.headers as Record<string, string>) }; if (opts.token) headers.Authorization = `Bearer ${opts.token}`; if (opts.body && !(opts.body instanceof FormData)) headers["Content-Type"] = "application/json"; return fetch(`${API_BASE_URL}${path}`, { ...opts, headers }); }
export async function login(email: string, password: string, orgId?: string): Promise<{ token: string; user: unknown }> { const res = await apiFetch("/auth/login", { method: "POST", body: JSON.stringify({ email, password, ...(orgId ? { orgId } : {}) }) }); if (!res.ok) throw new Error(`Login failed ${res.status}`); return res.json(); }
export async function listWorkspaces(token: string): Promise<any> { const res = await apiFetch("/workspaces", { token }); if (!res.ok) throw new Error(`Workspaces failed ${res.status}`); return res.json(); }
export async function uploadDocument(projectId: string, file: File, token: string): Promise<unknown> { const form = new FormData(); form.append("file", file); const res = await apiFetch(`/projects/${projectId}/documents?sync=true`, { method: "POST", body: form, token }); if (!res.ok) throw new Error(`Upload failed ${res.status}`); return res.json(); }
export async function createConversation(projectId: string, token: string): Promise<{ id: string }> { const res = await apiFetch(`/projects/${projectId}/conversations`, { method: "POST", token, body: JSON.stringify({}) }); if (!res.ok) throw new Error("Create conversation failed"); return res.json(); }
export async function sendMessage(conversationId: string, content: string, token: string): Promise<any> { const res = await apiFetch(`/conversations/${conversationId}/messages`, { method: "POST", token, body: JSON.stringify({ content }) }); if (!res.ok) throw new Error("Send message failed"); return res.json(); }
export async function getConversation(conversationId: string, token: string): Promise<unknown> { const res = await apiFetch(`/conversations/${conversationId}`, { token }); if (!res.ok) throw new Error("Get conversation failed"); return res.json(); }
export async function listArtifacts(projectId: string, token: string): Promise<any> { const res = await apiFetch(`/projects/${projectId}/artifacts`, { token }); if (!res.ok) throw new Error("List artifacts failed"); return res.json(); }
export async function getArtifact(artifactId: string, token: string): Promise<any> { const res = await apiFetch(`/artifacts/${artifactId}`, { token }); if (!res.ok) throw new Error("Get artifact failed"); return res.json(); }
export async function updateArtifact(artifactId: string, updates: any, token: string): Promise<any> { const res = await apiFetch(`/artifacts/${artifactId}`, { method: "PATCH", token, body: JSON.stringify(updates) }); if (!res.ok) throw new Error("Update artifact failed"); return res.json(); }
export async function regenerateArtifact(artifactId: string, feedback: string, token: string, expectedVersion?: number): Promise<any> { const res = await apiFetch(`/artifacts/${artifactId}/regenerate`, { method: "POST", token, body: JSON.stringify({ feedback, expectedVersion }) }); if (!res.ok) throw new Error(`Regeneration failed ${res.status}`); return res.json(); }
export async function getJourneyState(projectId: string, token: string): Promise<any> { const res = await apiFetch(`/projects/${projectId}/journey`, { token }); if (!res.ok) throw new Error("Get journey state failed"); return res.json(); }
export async function transitionJourney(projectId: string, stage: string, status: string, token: string, version?: number, reason?: string): Promise<any> { const res = await apiFetch(`/projects/${projectId}/journey/transition`, { method: "POST", token, body: JSON.stringify({ stage, status, version, reason }) }); if (!res.ok) throw new Error(`Journey transition failed ${res.status}`); return res.json(); }
export async function getDashboard(projectId: string, token: string): Promise<any> { const res = await apiFetch(`/projects/${projectId}/dashboard`, { token }); if (!res.ok) throw new Error(`Dashboard failed ${res.status}`); return res.json(); }
export async function getProjectActivity(projectId: string, token: string): Promise<any> { const res = await apiFetch(`/projects/${projectId}/activity`, { token }); if (!res.ok) throw new Error("Get project activity failed"); return res.json(); }
