import crypto from "crypto";
import { PrismaClient } from "@prisma/client";
import { IDocumentAggregateRepository,DocumentEntity,DocumentChunkEntity } from "../interfaces";
import { withTenant,assertTenant } from "../../db/tenant";
function mapDocument(d:any):DocumentEntity{return{id:d.id,orgId:d.orgId,projectId:d.projectId,filename:d.filename,doc_type:String(d.type),file_size:Number(d.fileSize??0),parsedStatus:d.parsedStatus,storage_key:d.storageKey??d.storageUrl??null,createdAt:d.createdAt,updatedAt:d.updatedAt??d.createdAt};}
export class PostgresDocumentAggregateRepository implements IDocumentAggregateRepository{
 constructor(private readonly prisma:PrismaClient){}
 async createDocument(orgId:string,projectId:string,data:{filename:string;docType:string;fileSize:number;storageKey?:string;uploadedBy?:string}){assertTenant(orgId);if(!data.uploadedBy)throw new Error("uploadedBy is required");return withTenant(this.prisma as never,orgId,async(tx:unknown)=>{const d=await(tx as any).document.create({data:{orgId,projectId,filename:data.filename,type:data.docType,storageUrl:data.storageKey??"",parsedStatus:"pending",uploadedBy:data.uploadedBy}});return mapDocument({...d,fileSize:data.fileSize,storageKey:data.storageKey});});}
 async findDocumentById(orgId:string,id:string){assertTenant(orgId);return withTenant(this.prisma as never,orgId,async(tx:unknown)=>{const d=await(tx as any).document.findFirst({where:{id,orgId}});return d?mapDocument(d):null;});}
 async listDocumentsByProject(orgId:string,projectId:string){assertTenant(orgId);return withTenant(this.prisma as never,orgId,async(tx:unknown)=>(await(tx as any).document.findMany({where:{projectId,orgId},orderBy:{createdAt:"desc"}})).map(mapDocument));}
 async updateParsedStatus(orgId:string,id:string,status:"pending"|"parsed"|"failed"){assertTenant(orgId);return withTenant(this.prisma as never,orgId,async(tx:unknown)=>{const p=tx as any,d=await p.document.updateMany({where:{id,orgId},data:{parsedStatus:status}});if(d.count!==1)throw new Error("Document not found");return mapDocument(await p.document.findFirstOrThrow({where:{id,orgId}}));});}
 async addChunks(orgId:string,documentId:string,cs:Array<{chunkIndex:number;content:string;pageNumber?:number;embedding?:number[]}>){assertTenant(orgId);return withTenant(this.prisma as never,orgId,async(tx:unknown)=>{const p=tx as any;if(!(await p.document.findFirst({where:{id:documentId,orgId}})))throw new Error("Document not found");const out:DocumentChunkEntity[]=[];for(const c of cs){const id=crypto.randomUUID(),v=c.embedding?.length?`[${c.embedding.join(",")}]`:null;if(v)await p.$executeRawUnsafe("INSERT INTO document_chunks (id,document_id,org_id,chunk_text,embedding,page_ref) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5::vector,$6)",id,documentId,orgId,c.content,v,c.pageNumber??null);else await p.$executeRawUnsafe("INSERT INTO document_chunks (id,document_id,org_id,chunk_text,page_ref) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5)",id,documentId,orgId,c.content,c.pageNumber??null);out.push({id,orgId,documentId,chunk_index:c.chunkIndex,content:c.content,page_number:c.pageNumber??null,embedding:c.embedding??null,createdAt:new Date()});}return out;});}
 async searchSimilarChunks(orgId:string,projectId:string,q:number[],topK:number){assertTenant(orgId);if(q.length!==1536)throw new Error("query embedding must have 1536 dimensions");const limit=Math.max(1,Math.min(20,Math.floor(topK))),v=`[${q.join(",")}]`;return withTenant(this.prisma as never,orgId,async(tx:unknown)=>{const rows=await(tx as any).$queryRawUnsafe(`SELECT c.id,c.org_id AS "orgId",c.document_id AS "documentId",c.chunk_text AS content,c.page_ref AS "page_number",c.created_at AS "createdAt",1-(c.embedding <=> $1::vector) AS score FROM document_chunks c JOIN documents d ON d.id=c.document_id WHERE c.org_id=$2::uuid AND d.org_id=$2::uuid AND d.project_id=$3::uuid AND c.embedding IS NOT NULL ORDER BY c.embedding <=> $1::vector ASC LIMIT $4`,v,orgId,projectId,limit);return rows.map((r:any)=>({...r,chunk_index:0,embedding:null,score:Number(r.score)}));});}
 async deleteDocument(orgId:string,id:string){assertTenant(orgId);return withTenant(this.prisma as never,orgId,async(tx:unknown)=>{const p=tx as any;const d=await p.document.findFirst({where:{id,orgId}});if(!d)throw new Error("Document not found");await p.document.delete({where:{id}});});}
}
